[package]
name = "file_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1" }
tokio = { version = "1", features = [
  "net",
  "fs",
  "macros",
  "io-util",
  "rt-multi-thread",
] }
log = { version = "0.4" }
fern = { version = "0.6", features = ["colored"] }
humantime = "2"
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite"] }
rand = "0.8"
bfsp = { git = "https://github.com/Billy-s-E2EE-File-Server/bfsp.git" }
#bfsp = { path = "../bfsp" }
async-trait = { version = "0.1" }
once_cell = "1"
futures = { version = "0.3", features = ["executor"] }
thiserror = "1"
biscuit-auth = { version = "4" }

serde = { version = "1" }
serde_json = { version = "1" }
