# fly.toml app configuration file generated for encrypted-file-server-spring-surf-6898 on 2024-02-15T10:44:17-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'encrypted-file-server'
primary_region = 'ord'

[[services]]
  protocol = "udp"
  internal_port = 9999
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [[services.ports]]
    port = 9999

[http_service]
  internal_port = 80
  force_https = false

[env]
  RUST_BACKTRACE="1"
  TOKEN_PUBLIC_KEY="d27fb9c11d7608f86aa9e90a00133d58688b2fe4e7903a35199a25f7e905f658"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
