[package]
name = "cli_enc"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0.72"
bfsp = { path = "../bfsp" }
blake3 = "1"
chacha20poly1305 = "0.10.1"
fern = "0.6.2"
humantime = "2.1.0"
log = "0.4.19"
rkyv = "0.7.42"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["full"] }
directories-next = "2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Storage"] }
wasm-timer = "0.2"
