name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v23
    - name: Build
      run: nix develop --command cargo build --all --verbose
    - name: Run tests
      run: nix develop --command cargo test --all --verbose
    - name: Check formatting
      run: nix develop --command cargo fmt --check --all
