name: Deploy to Fly
on:
  push:
    branches: [ "*" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Fly
    runs-on: windows-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      - run: .\flyctl.exe auth login ${{ secrets.FLY_API_TOKEN }}
      - run: .\flyctl.exe deploy --remote-only -a billy-rust
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
